### ISSUE TITLE
server-side rendering support for soundmanager2.js in Node

### ISSUE THREAD

**Issue by shubhamfse** [leoasis/react-sound#21]
It is showing me a ReferenceError:window is not defined in  node_modules/soundmanager2/script/soundmanager2.js !!

How can we use soundmanager2 for server rendered scripts on node.On webpack it's working fine bcoz the browser can recognise window object.

**Comment by hyperh** [comment]
+1 Same issue here

**Comment by hyperh** [comment]
I did this to fix it https://github.com/kadirahq/flow-router/issues/628
```
import React, { Component } from 'react';
import song from '../assets/test.mp3';

const isBrowser = typeof window !== 'undefined';
const Sound = isBrowser ? require('react-sound') : null;

// eslint-disable-next-line react/prefer-stateless-function
export default class MusicPlayer extends Component {
  render() {
    return (
      <div>
        {
          isBrowser ?
            <Sound
              url={song}
              playStatus={Sound.status.PLAYING}
            /> : null
        }
      </div>
    );
  }
}

```

**Comment by shubhamfse** [comment]
It didn't work for me .Instead I used the following solution:

> var fakeDOM = require('fake-dom');
> var window = fakeDOM.window;
> var document = fakeDOM.document;

**Comment by DvirSh** [comment]
@hyperh The thing is that this solution causes the browser to complain that
```
React attempted to reuse markup in a container but the checksum was invalid.
This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting.
React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server:
```

So now I'm trying to understand wether this has any meaning - does this cancel SSR? Or maybe since it is just a slight difference in the sound component then it is irrelevant and react handles that well?
Anyone seen this before?

**Comment by leoasis** [comment]
@DvirSh yeah, @hyperh's solution makes the component hierarchy different compared to what it ends up being rendered in the client. I'd be happy to accept a PR that adds support for server side rendering. I think the idea would be to conditionally require soundManager and do the initialization only in the client, where the library works. In the server, it should just ignore that. The rest would still work I think, since the component renders `null` and it only starts doing work in `componentDidMount`, which is not triggered in the server.

If anybody wants to help with this, let me know!

**Comment by luntegg** [comment]
I can't solve this problem this too.

**Comment by luntegg** [comment]
I use MERN – https://github.com/Hashnode/mern-starter (react, redux, webpack, nodejs, express)
And this component.

When I include component 

`    import Sound from 'react-sound';`

and try start the server, I have `"window is not defined"` error from webpack server rendering.

But if I comment this line and start the server, all will be fine. After that I can uncomment this line and component will be work, because when the server is running, changes don't triggered server rendering (only front rendering).

If I try

 ```
   if (typeof window !== 'undefined') {
        const Sound = require('react-sound');
    }

```
And in render

```
    render() {
        return (
            <div>
                <Sound playStatus={Sound.status.STOPPED} url="" />
            </div>
        );
    }

```
I have `ReferenceError: Sound is not defined` error on front rendering (after webpack).

If I try (`var`, not `const`)
```
    if (typeof window !== 'undefined') {
        var Sound = require('react-sound');
    }
```

I have `TypeError: Cannot read property 'status' of undefined` error on front rendering.

**Comment by leoasis** [comment]
I wrote in a comment above the idea to make this work on the server. I'm happy to accept a PR that does that, as I don't have time to work on it right now (and I'm not using server side rendering where I use this)

**Comment by luntegg** [comment]
I solved this problem in your component, but in my node_modules it's all in ES5, but here (github) your code in ES6. Maybe my pull request is bad, I don't know.

**Comment by leoasis** [comment]
Fixed by @luntegg in the latest version, now published, thank you all!
