### ISSUE TITLE
Сreate a method to stop playback of all sounds

### ISSUE THREAD

**Issue by olgenn** [leoasis/react-sound#22]
Is it possible to create a method to stop playback of all sounds?

**Comment by leoasis** [comment]
Can you provide an example so that I can understand your use case a bit more?

**Comment by DevLab2425** [comment]
@olgenn @leoasis 

Here's something I'm using. Does the job for now, but would love to see this component extended to be able to config and control sounds on a global level. 

Since `soundManager` exists on the global namespace, we can access it directly.
```javascript
onMuteButtonClick (ev) {
  this.setState({
    allMuted: !this.state.allMuted
  });

  this.state.allMuted ? this.unmuteAllSounds() : this.muteAllSounds();
}

muteAllSounds () {
  // we can easily access soundManager here
  window.soundManager.muteAll();
}

unmuteAllSounds () {
  // same to unmute
  window.soundManager.unmuteAll();
}

  render () {

    return (
      <div className="wrapper">
        <MuteButton isMuted={this.state.allMuted} onButtonClick={this.onMuteButtonClick} />
      </div>
    );

  }
```

**Comment by vmasto** [comment]
I just opened the issues so that I could post the same :)

@leoasis what do you think would be a good solution for this?

This is mainly helpful when you have a lot of different players/sound instances on the same page.

@DevLab2425's workaround is what I'm also using but I think it would be better if: 

a) The library took it upon itself to simply stop all sounds before playing a new one or
b) We provide a declarative way to doing this via props, which is user configurable.
c) other idea?

Probably leaving it up to the user (like in option `b`) is more flexible, there could be some use-cases where someone would need multiple sounds to be played on the same page (perhaps a drum machine/instrument emulator of some kind?).

**Comment by leoasis** [comment]
Hi all!

The idea for this component is to be able to control its state. You can already control wether it's playing or not with its `playStatus` prop. So, in order to achieve what you want, you should have a way to centralize the "mute all sounds" state in a component (or somewhere else), and use that state to determine what the `playStatus` should be:

```js
class Example extends React.Component {
  constructor(props) {
    super(props);
    this.state = { 
      muteAllSounds: false,
      soundState: {
        playStatus: Sound.status.PLAYING,
        position: 0
      }
    };
  }

  handleMuteToggle() {
    this.setState({ muteAllSounds: !this.state.muteAllSounds });
  }

  render() {
    return (
      <div>
        <Sound playStatus={this.state.muteAllSounds ? Sound.status.PAUSED : this.state.soundState.playStatus} ... />
        <button onClick={this.handleMuteToggle.bind(this)>
          {this.state.muteAllSounds ? 'Unmute all sounds' : 'Mute all sounds'}
        </button>
      </div>
    );
  }
}
```

Notice how the `Sound` here will be paused if the `muteAllSounds` flag is true, and it will delegate to `soundState.playStatus` otherwise.

**Comment by caselas** [comment]
Would it be reasonable to add the [`onpause`](http://www.schillmania.com/projects/soundmanager2/doc/#smsound-onpause) and [`onstop`](http://www.schillmania.com/projects/soundmanager2/doc/#smsound-onstop) callbacks within `createSound()` to allow for a Sound component to manage its own state in response to soundManager pause/stop events?

This would allow for `soundManager.pauseAll()` or `soundManager.stopAll()` without tightly coupling individual Sound components or various control components.

If so, I'm happy to open a PR :)

**Comment by chadwilken** [comment]
@caselas I could really make use out of onpause and onstop callbacks. We render quite a few of these on one page and that would be handy to allow stopping all others when another is played.

**Comment by leoasis** [comment]
@caselas yeah I think that is a reasonable addition to the library, give it a go! Thanks for contributing!

**Comment by chadwilken** [comment]
@leoasis and @caselas I opened a PR for this. Let me know if you need anything updated.

**Comment by leoasis** [comment]
Closing since this is already a bit dated, and seems all concerns have been addressed. Feel free to reopen otherwise

**Comment by khusan-dev** [comment]
> ```js
> window.soundManager
> ```

Thanks. I used `window.soundManager.stopAll();` for stop all sound.
