### ISSUE TITLE
soundmanger cannot initialize if react-sound is loaded on the fly

### ISSUE THREAD

**Issue by bergkampho** [leoasis/react-sound#9]
In react-sound, soundmanger will initialize when the DOM is ready. However, for my project, react-sound will be injected after DOM is ready. Thus, soundManager.createSound is not working when react-sound componentDidMount.

I found that soundmanger will provide `beginDelayedInit`. Can we make use of it?
https://github.com/scottschiller/SoundManager2/blob/master/script/soundmanager2.js#L6271

**Comment by leoasis** [comment]
How are you injecting `react-sound` afterwards? There is code already in place to see if sound manager is already initialized and act accordingly, so would like to understand the use case you're having, and why the current way doesn't work

**Comment by Secretmapper** [comment]
I just faced the same issue as OP. In my case, using it directly works fine, but lazy-loading a bundle generated by webpack fails.

It does indeed seem weird since code for pending calls are already in the package. I'll try to investigate this tomorrow and hopefully submit a PR or a sample repo that outlines the bug.

**Comment by leoasis** [comment]
Awesome @Secretmapper this would be super helpful, thanks!
